dist: trusty
sudo: false
language: python
python: 3.6
cache:
  apt: true
  pip: true
install:
  - pip install -U pip
  - pip install cython
  - pip install -U ucca
  - python -m spacy download en_core_web_md
env:
  global:
    - SCRIPTS=https://raw.githubusercontent.com/UniversalConceptualCognitiveAnnotation/docs/master/scripts
    - secure: "1vTw5XxFVOPeipow42gzKS9Hq2wEkxz/aXNERGtppKbm+B54lHB/5pZDwnbqrqAbgQSgZIeGJFNNc0svVIbkV0eEG1UrpiOpL2gWDOb+3gEAKWwvqbF4dEMNhTRWqBPuMtSQrZmx7ny0FI4fZOyuCp7vylMGzclH+dJrYvtFgjNJcZokjdQ69ZrPEGnXg3tfzKrLpMZD/Q+XTdk5jKbk+rZ+DyznAGFgXtVdIwodUB47yWclUgXH9ixDsuY4Cy9Zz8tYBg9hLcTDPDXkNo/UHuRFCmO1kC7Q/KumaJvyL8LvRZfkheP4yEiYKZyv4Ll9USeST389q7wktCpfXdankgR+s5vyoByn1NXwdEcHru7R9uyY/8d+js4VE4l4rR2ftNgFC9wzPdWRrxcw7PNzwpn7ttTDxPQPyXRDO3LXA9AQcghR+zsPwWji1//QYnUkwuR7+HEj+NdhSeutkxPtvlAG7UdmjSA2RGP7IlTghOfngsFMdrzNUoPqjidv2rAZyR2o9k8O2KhlwU6NCEgX74VFWdS5CuAxV5QFVKxCngSg4Up2sALDVU9m3fq0AtqdiTyHwA69iBbQ5eU+3jz63pSRln16EXDEqxMxIx6ayuktr9aURhVB6c5X7IJQudQ0jioUlw8g6iPUZmb+2x9bEWg53G2W+Zane2fJ4WzJwTc="
jobs:
  include:
    - script: python -m scripts.validate xml --no-linkage
    - script: curl $SCRIPTS/split_to_sentences.sh | bash
    - stage: convert
      script: curl $SCRIPTS/validate_sentences.sh | bash -s -- --no-linkage
      env: FORMAT=validate
    - script: curl $SCRIPTS/sentences_to_xml.sh | bash
      env: FORMAT=xml
    - script: curl $SCRIPTS/tupa.sh | bash
      env: FORMAT=tupa
    - script: curl $SCRIPTS/visualize.sh | bash
      env: FORMAT=visualize
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=amr
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=export
    - script: curl $SCRIPTS/convert.sh | bash -s $FORMAT
      env: FORMAT=txt
    - stage: evaluate
      script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=sdp
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conll
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=conllu
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=amr
    - script: curl $SCRIPTS/evaluate.sh | bash -s $FORMAT
      env: FORMAT=export
after_success: curl $SCRIPTS/push.sh | bash

